services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    networks:
      - lake-house-network

  postgres-metastore:
    image: postgres:17.2-bookworm
    hostname: postgres-metastore
    expose:
      - "5432"
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hive_db
    networks:
      - lake-house-network

  hive-metastore:
    image: "my-hive:latest"
    hostname: hive-metastore
    ports:
      - "9083:9083" # Metastore Thrift
    volumes:
      - ./hive/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: postgres-metastore
      METASTORE_TYPE: postgres
    networks:
      - lake-house-network

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - 8085:8080
    volumes:
      - ./trino:/etc/trino/
    networks:
      - lake-house-network

  source-mssql:
    image: adventureworks2022-mssql:latest
    container_name: source-mssql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - lake-house-network

networks:
  lake-house-network:
